Multicore Ingress bug and header_flit
stevehoover/warp-v pull request #67
Opened 2021-05-23 11:16 UTC by vineetjain07

This PR contains -
1) Index in $csr_core for NUM_CORES > 1 (without this, Cores>2 were failing)
2) Shift the $header_flit field to {(msb)VC - SRC - DEST(lsb)}
3) Fix for Ingress buffer, by blocking flits for PKTRD(if flit is invalid on its 1st cycle) until it replays with a valid flit.

2021-05-23 16:33 UTC, stevehoover requested changes
I don't understand well enough to approve. Needs commenting.

2021-05-23 16:33 UTC, stevehoover commented on warp-v.tlv
> +   endmodule
Probably done by your text editor. You might want to change your editor's setting for this.

2021-05-23 16:33 UTC, stevehoover commented on warp-v.tlv
> +                          $negedge_pktrd ? '0 : $RETAIN;
$RETAIN makes this state. State should generally have a $reset case. I don't think this needs to be state. I don't actually understand how this expression has any impact. Isn't $posedge_pktrd a pulse? So this expression will pulse only if ! $trans_valid, in which case there's nothing to block?? In any case, the first issue is that a clear comment describing this case is needed.

2021-05-23 19:06 UTC, vineetjain07 commented on warp-v.tlv
> +   endmodule
done

2021-05-23 19:14 UTC, vineetjain07 commented on warp-v.tlv
> +                          $negedge_pktrd ? '0 : $RETAIN;
Yes, $posedge_pktrd is a pulse. So, $pktrd_blocked is asserted on $posedge_pktrd only if  ! $trans_valid, and it should remain HIGH until $do_pktrd is low.

2021-05-28 02:18 UTC, vineetjain07 commented
Fixed - 
1) typo for GoodPathMask in docs.
2) speculative CSR pktrd.
3) VIZ for /bank[*]

2021-05-28 19:49 UTC, stevehoover approved these changes

2021-05-28 20:04 UTC, merged